plinth/modules/networks/urls.py
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

"""
URLs for the Network module
"""

from django.conf.urls import patterns, url


urlpatterns = patterns(
    'plinth.modules.networks.networks',
    url(r'^sys/networks/$', 'index', name='index'),
    url(r'^sys/networks/(?P<uuid>[\w.@+-]+)/edit/$',
        'edit', name='edit'),
    url(r'^sys/networks/(?P<uuid>[\w.@+-]+)/activate/$',
        'activate', name='activate'),
    url(r'^sys/networks/(?P<uuid>[\w.@+-]+)/deactivate/$',
        'deactivate', name='deactivate'),
    url(r'^sys/networks/scan/$', 'scan', name='scan'),
    url(r'^sys/networks/add/$', 'add', name='add'),
    url(r'^sys/networks/add/ethernet/$', 'add_ethernet', name='add_ethernet'),
    url(r'^sys/networks/add/wifi/(?:(?P<ssid>[^/]+)/)?$', 'add_wifi',
        name='add_wifi'),
    url(r'^sys/networks/(?P<uuid>[\w.@+-]+)/delete/$',
        'delete', name='delete'),
)

plinth/modules/networks/forms.py
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

from django import forms
from django.core import validators
from gettext import gettext as _

from plinth import network


class ConnectionTypeSelectForm(forms.Form):
    """Form to select type for new connection."""
    connection_type = forms.ChoiceField(
        label=_('Connection Type'),
        choices=[(key, value)
                 for key, value in network.CONNECTION_TYPE_NAMES.items()])


class AddEthernetForm(forms.Form):
    """Form to create a new ethernet connection."""
    name = forms.CharField(label=_('Connection Name'))
    zone = forms.ChoiceField(
        label=_('Firewall Zone'),
        help_text=_('The firewall zone will control which services are \
available over this interfaces. Select Internal only for trusted networks.'),
        choices=[('external', 'External'), ('internal', 'Internal')])
    ipv4_method = forms.ChoiceField(
        label=_('IPv4 Addressing Method'),
        choices=[('auto', 'Automatic (DHCP)'),
                 ('shared', 'Shared'),
                 ('manual', 'Manual')])
    ipv4_address = forms.CharField(
        label=_('Address'),
        validators=[validators.validate_ipv4_address],
        required=False)


class AddWifiForm(forms.Form):
    """Form to create a new wifi connection."""
    name = forms.CharField(label=_('Connection Name'))
    zone = forms.ChoiceField(
        label=_('Firewall Zone'),
        help_text=_('The firewall zone will control which services are \
available over this interfaces. Select Internal only for trusted networks.'),
        choices=[('external', 'External'), ('internal', 'Internal')])
    ssid = forms.CharField(
        label=_('SSID'),
        help_text=_('The visible name of the network.'))
    mode = forms.ChoiceField(
        label=_('Mode'),
        choices=[('infrastructure', 'Infrastructure'),
                 ('ap', 'Access Point'),
                 ('adhoc', 'Ad-hoc')])
    auth_mode = forms.ChoiceField(
        label=_('Authentication Mode'),
        help_text=_('Select WPA if the wireless network is secured and \
requires clients to have the password to connect.'),
        choices=[('wpa', 'WPA'), ('open', 'Open')])
    passphrase = forms.CharField(
        label=_('Passphrase'),
        validators=[validators.MinLengthValidator(8)],
        required=False)
    ipv4_method = forms.ChoiceField(
        label=_('IPv4 Addressing Method'),
        choices=[('auto', 'Automatic (DHCP)'),
                 ('shared', 'Shared'),
                 ('manual', 'Manual')],
        help_text=_('Select Automatic (DHCP) if you are connecting to an \
existing wireless network. Shared mode is useful when running an Access \
Point.'))
    ipv4_address = forms.CharField(
        label=_('Address'),
        validators=[validators.validate_ipv4_address],
        required=False)

plinth/modules/networks/templates/connections_add.html
{% extends "base.html" %}
{% comment %}
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}

{% load bootstrap %}

{% block content %}

  <div class="row">
    <div class="col-sm-8">
      <form class="form" method="post">
        {% csrf_token %}

        {{ form|bootstrap }}

        <input type="submit" class="btn btn-primary" value="Create..."/>

      </form>
    </div>
  </div>

{% endblock %}

{% block page_js %}
  <script>
    $('#id_type').focus();
  </script>
{% endblock %}

plinth/modules/networks/templates/connections_create.html
{% extends "base.html" %}
{% comment %}
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}

{% load bootstrap %}

{% block content %}

  <div class="row">
    <div class="col-sm-8">
      <form class="form" method="post">
        {% csrf_token %}

        {{ form|bootstrap }}

        <input type="submit" class="btn btn-primary" value="Create Connection"/>

      </form>
    </div>
  </div>

{% endblock %}

{% block page_js %}

  <script type="text/javascript">
    (function($) {

    if ($("#id_ipv4_method").prop("value") != "manual") {
      $("#id_ipv4_address").prop("readOnly", true);
    }
    $("#id_name").focus();

    $("#id_ipv4_method").change(function() {
      if ($("#id_ipv4_method").prop("value") == 'manual') {
        $("#id_ipv4_address").prop("readOnly", false);
        $("#id_ipv4_address").prop("required", true);
      } else {
        $("#id_ipv4_address").val("");
        $("#id_ipv4_address").prop("readOnly", true);
        $("#id_ipv4_address").prop("required", false);
      }
    });

    })(jQuery);
  </script>

{% endblock %}

plinth/modules/networks/templates/connections_delete.html
{% extends "base.html" %}
{% comment %}
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}

{% load bootstrap %}

{% block content %}

  <h3>Delete Connection <em>{{ name }}</em></h3>

  <p>Delete connection permanently?</p>

  <form class="form" method="post">
    {% csrf_token %}

    <input type="submit" class="btn btn-md btn-primary"
           value="Delete {{ name }}"/>

    <a href="{% url 'networks:index' %}" role="button"
       class="btn btn-md btn-primary">Cancel</a>
  </form>

{% endblock %}

plinth/modules/networks/templates/connections_edit.html
{% extends "base.html" %}
{% comment %}
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}

{% load bootstrap %}

{% block content %}

  <div class="row">
    <div class="col-sm-8">
      <form class="form" method="post">
        {% csrf_token %}

        {{ form|bootstrap }}

        <input type="submit" class="btn btn-primary" value="Edit Connection"/>

      </form>
    </div>
  </div>

{% endblock %}

{% block page_js %}

  <script type="text/javascript">
    (function($) {

    if ($("#id_ipv4_method").prop("value") != "manual") {
      $("#id_ipv4_address").prop("readOnly", true);
    }
    $("#id_name").focus();

    $("#id_ipv4_method").change(function() {
      if ($("#id_ipv4_method").prop("value") == "manual") {
        $("#id_ipv4_address").prop("readOnly", false);
        $("#id_ipv4_address").prop("required", true);
      } else {
        $("#id_ipv4_address").val("");
        $("#id_ipv4_address").prop("readOnly", true);
        $("#id_ipv4_address").prop("required", false);
      }
    });

    })(jQuery);
  </script>

{% endblock %}

plinth/modules/networks/templates/connections_list.html
{% extends "base.html" %}
{% comment %}
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}

{% load bootstrap %}

{% block page_head %}
  <style type="text/css">
    .connection-edit-label {
      display: inline-block;
      width: 40%;
    }
    .connection-type-label {
      display: inline-block;
      width: 20%;
    }
    .list-group-item .btn {
      margin: -5px 0;
    }
  </style>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col-sm-6">
      <div class="list-group">
        {% for connection in connections %}
          <div class="list-group-item clearfix">
            <a href="{% url 'networks:delete' connection.uuid %}"
               class="btn btn-default btn-sm pull-right"
               role="button" title="Delete connection {{ connection.name }}">
              <span class="glyphicon glyphicon-trash"
                    aria-hidden="true"></span>
            </a>

            <a class="connection-edit-label"
               href="{% url 'networks:edit' connection.uuid %}"
               title="Edit connection {{ connection.name }}">
              {{ connection.name }}
            </a>

            <span class="connection-type-label">{{ connection.type }}</span>

            {% if connection.is_active %}
            <div class="btn-group">
              <button type="button"
                      class="btn btn-success btn-xs dropdown-toggle"
                      data-toggle="dropdown" aria-expanded="false">
                Active <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a href="{% url 'networks:deactivate' connection.uuid %}">
                    Deactivate
                  </a>
                </li>
              </ul>
            </div>
            {% else %}
            <div class="btn-group">
              <button type="button"
                      class="btn btn-warning btn-xs dropdown-toggle"
                      data-toggle="dropdown" aria-expanded="false">
                Not Active <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a href="{% url 'networks:activate' connection.uuid %}">
                    Activate
                  </a>
                </li>
              </ul>
            </div>
            {% endif %}

          </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}

plinth/modules/networks/templates/connections_type_select.html
{% extends "base.html" %}
{% comment %}
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}

{% load bootstrap %}

{% block content %}

  <div class="row">
    <div class="col-sm-8">
      <form class="form" method="post">
        {% csrf_token %}

        {{ form|bootstrap }}

        <input type="submit" class="btn btn-primary" value="Create..."/>

      </form>
    </div>
  </div>

{% endblock %}

{% block page_js %}
  <script>
    $('#id_type').focus();
  </script>
{% endblock %}

plinth/modules/networks/templates/wifi_scan.html
{% extends "base.html" %}
{% comment %}
#
# This file is part of Plinth.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
{% endcomment %}

{% load bootstrap %}

{% block content %}

  <div class="row">
    <div class="col-sm-6">
      <div class="list-group">
        {% for access_point in access_points %}
        <div class="list-group-item clearfix">
          {% if access_point.ssid %}
          <a display="inline-block" width="40%"
             href="{% url 'networks:add_wifi' access_point.ssid %}">
             {{ access_point.ssid }}
          </a>
          {% else %}
          --
          {% endif %}
          <span class="btn btn-primary btn-xs pull-right">
            {{ access_point.strength }}%
          </span>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% endblock %}